### PR TITLE
Remove activity tab

### PR DESCRIPTION
**Pull request by frankhereford**
# Intent

This PR intends to close https://github.com/cityofaustin/atd-data-tech/issues/16550.

# Testing

https://deploy-preview-87--atd-product.netlify.app/

* Visit a product, and observe that the `Activity` tab is gone.
* Become comfortable that I have removed the `<Comments />` component entirely.

### CODE REVIEW

**Review by chiaberry — APPROVED** [review]
activity be gone!

**Review by amenity — APPROVED** [review]
Perfect, thanks! 🚢 👍🏻

**Review by mddilley — APPROVED** [review]
Tested on the deploy preview, and I don't see the activity tab anymore. 👋 Thanks for the code cleanup as well! 🧹 🚢

**Review by roseeichelmann — APPROVED** [review]
:ship: looks good!!

**Review by johnclary — APPROVED** [review]
nice! ✌️

**Comment by chiaberry** [comment]
It would appear we should not have been cheering for the activity tab to be *fully* gone
https://github.com/cityofaustin/atd-data-tech/issues/16836

**Pull request merged**
