### PR TITLE
9376 update staff listing

### PR DESCRIPTION
**Pull request by roseeichelmann**
Closes https://github.com/cityofaustin/atd-data-tech/issues/9376

Updated Mateo's title to "Head of Software Engineering"
Moved John to "Alumni"
Added Peggy, Rose, and Rebecca to team

### CODE REVIEW

**Review by mateoclarke — CHANGES_REQUESTED** [review]
All the code looks good but since the jpg that Peggy gave us for her headshot isn't a perfect square, the automatic circle cropping makes it look too much like an oval. 

Could you try using this alternative jpg I photoshopped into a square instead?
peggy_maccallum

**Review by patrickm02L — APPROVED** [review]
Looks good! Thanks for updating Peggy's head shot. Looks kinda trippy. 😵‍💫

Screen Shot 2022-06-13 at 2 31 44 PM

Ship it! 🤘

**Review by mateoclarke — APPROVED** [review]
mason_ramsey

**Comment by roseeichelmann** [comment]
Woohoo! Should I delete this branch now?

**Comment by johnclary** [comment]
thanks @roseeichelmann!

**Comment by patrickm02L** [comment]
> Woohoo! Should I delete this branch now?

Yes, please do.

**Pull request merged**
