### PR TITLE
Update ATD Staff Page

### PR DESCRIPTION
**Pull request by frankhereford**
This PR intends to close cityofaustin/atd-data-tech/issues/6777.
This PR also intends to close cityofaustin/atd-data-tech/issues/7067.

- [x] Add Frank
- [x] Remove Surbhi
- [x] Update Amenity's title to "Head of Product"
- [x] Update Nadin's title to "Product Delivery Manager" 
- [x] Create a alumni section containing entries for:
  - [x] Jace
  - [x] Mike
  - [x] Janet
  - [x] Annie
  - [x] Jorge
  - [x] Surbhi

### CODE REVIEW

**Review by mateoclarke — APPROVED** [review]
🙌 

pow-wow-go-team

**Comment by amenity** [comment]
@frankhereford - would it be possible to sneak in one more update here? @Nadin-Nader is taking the title "Product Delivery Manager"

**Comment by frankhereford** [comment]
@amenity - no worries on the additional change! I have updated Nadin's title to "Product Delivery Manger."

I'm not sure if/where this app has a staging or preview instance, so if you'd like to see how this looks, please slack me and I'll send you the URL to mine.

Thanks!

**Review by amenity — APPROVED** [review]
Beautiful! 

@frankhereford - I checked the PR using the Netlify deploy preview we have set up:
Screen Shot 2021-09-27 at 3 33 53 PM

**Comment by johnclary** [comment]
yay @frankhereford! thanks!

lol @mateoclarke that sbtb gif

**Pull request merged**
