### PR TITLE
Increase hyperlink accessibility

### PR DESCRIPTION
**Pull request by RR216**
This PR closes: https://github.com/cityofaustin/atd-data-tech/issues/5530
This is the deploy preview: https://deploy-preview-70--atd-product.netlify.app/products/5150
Here are the details changed:
For `a` element:
- Remove text-decoration: none
- Swap in #1059AD* for color

From `.nav-link` class:
- Add text-decoration: none

The `.nav-link` class actually has always had `text-decoration: none` established, since there is a global link variable that enables `text-decoration: none`. Only removing it from `a` is needed.

### CODE REVIEW

**Review by roseeichelmann — APPROVED** [review]
Yay this looks great! The links are easily distinguishable now :sparkles:

**Review by johnclary — CHANGES_REQUESTED** [review]
@RR216 after looking elsewhere in the app, i see that we use the Bootstrap `link` class to apply a fancy underline link style that looks like this:

Screenshot 2023-08-01 at 4 59 21 PM

which you can see is fancy in contrast to our `.markdown-link` underline:

Screenshot 2023-08-01 at 4 59 37 PM

would be good to double-check with @amenity, but i think it would be better to use that `link` class instead. sorry i didn't catch this when we were pairing!

**Comment by RR216** [comment]
> @RR216 after looking elsewhere in the app, i see that we use the Bootstrap `link` class to apply a fancy underline link style that looks like this:
> 
> Screenshot 2023-08-01 at 4 59 21 PM
> which you can see is fancy in contrast to our `.markdown-link` underline:
> 
> Screenshot 2023-08-01 at 4 59 37 PM
> would be good to double-check with @amenity, but i think it would be better to use that `link` class instead. sorry i didn't catch this when we were pairing!

Change applied!

**Review by johnclary — APPROVED** [review]
fantastic! please hold off on merging until @amenity has a chance to review 😊

**Review by mddilley — APPROVED** [review]
Looks great! And, TIL how this app uses React Markdown. 🙏 🚀

**Review by amenity — APPROVED** [review]
Looks good, @RR216! Thanks.

**Pull request merged**
