### PR TITLE
10721 products page

### PR DESCRIPTION
**Pull request by roseeichelmann**
Fixes cityofaustin/atd-data-tech/issues/10721

Steps to test:

[Netlify link](https://deploy-preview-53--atd-product.netlify.app/products)

1. Navigate to the Products page, there should be 4 cards per row on a laptop/desktop view
2. Scale down breakpoints, tablet view will show 2 cards per row, mobile will show 1 card per row

### CODE REVIEW

**Review by frankhereford — APPROVED** [review]
So responsive -- this looks awesome!

**Review by mddilley — APPROVED** [review]
Looks great - nice to see more products on the screen on desktop! ✨

**Comment by patrickm02L** [comment]
Let's change the description text to black to match the Projects page. 

> Products are the solutions we build for our customers, including Knack apps, AMANDA apps, custom software, and data systems. We improve and extend our products over time so that they deliver continuous value to Austin Transportation as business needs evolve.

Then, this PR is good to go.

**Review by patrickm02L — APPROVED** [review]
Golden! 🤘

**Review by tillyw — APPROVED** [review]
tested, works great !

**Pull request merged**
