### PR TITLE
10722 about page

### PR DESCRIPTION
**Pull request by roseeichelmann**
Fixes cityofaustin/atd-data-tech/issues/10722

Test steps:
[
Netlify link](https://deploy-preview-54--atd-product.netlify.app/about)

1. Navigate to About page.
2. Check how everything looks
3. Resize to a tablet breakpoint. "How we work" section should have 2 columns and team pics should have 3 columns, then resize to mobile breakpoint, "How we work" section should have 1 column and team pics should have 2 columns.

### CODE REVIEW

**Comment by roseeichelmann** [comment]
Just waiting on that photo from Zach Berry and then I'll add him to the team section

**Review by frankhereford — APPROVED** [review]
Now, that's a sharp looking team!! 📸✨

I think this looks good and responds the way one expects at breakpoints. Code is sharp too.

All aboard! The 🚢 is ready to sail!

**Comment by patrickm02L** [comment]
Let's change the description text under About title to black.

> We leverage high quality data and modern tech to empower Austin Transportation staff to improve operations, make data-informed decisions, and deliver excellent mobility services to the Austin community. We solve real problems for real people.

Everything else is good to go!

**Review by mddilley — APPROVED** [review]
Awesome, looks great - thanks for making these enhancements! ✨ 🚢

**Review by tillyw — APPROVED** [review]
this looks great! breakpoints/columns look good at every size. thanks for making these updates ✨

**Review by patrickm02L — APPROVED** [review]
Good to go! 🤘

**Pull request merged**
