### PR TITLE
Add fellows to website

### PR DESCRIPTION
**Pull request by RR216**
This PR closes https://github.com/cityofaustin/atd-data-tech/issues/12604
This PR also closes https://github.com/cityofaustin/atd-data-tech/issues/12609
This is the deploy preview: https://deploy-preview-65--atd-product.netlify.app/about
New headshots were added to the assets folder, and the index.js file was changed to update fellow names, titles, pronouns, and image links. Please review the changes and thanks for the suggestions!

### CODE REVIEW

**Comment by frankhereford** [comment]
Rachel and I got to work on this one together, so I'm going to remove my request to review, but I think this work is 💯 🚀 🚢 🚢🚢🚢🚢!!!

**Comment by patrickm02L** [comment]
Recommend expanding the CIF Fellowship titles to:

Rachel - Software Developer Fellow
Madison - Design Fellow

**Review by johnclary — APPROVED** [review]
I dusted off my repo and spun this up. Looks fantastic! Thanks for doing this! Welcome aboard!!!

🚢 🚢 🚢 🚢 🚢 🚢 🚢

**Review by mddilley — APPROVED** [review]
Awesome work and welcome again! Glad to see y'all on the site. 🚀 🚢  🙌

**Review by patrickm02L — APPROVED** [review]
Thanks for making that title update. Everything looks perf! 🥏

**Pull request merged**
