### PR TITLE
updated Amenity's title

### PR DESCRIPTION
**Pull request by tillyw**
Fixes https://github.com/cityofaustin/atd-data-tech/issues/5395

Screen Shot 2021-03-09 at 12 41 23 PM

### CODE REVIEW

**Review by johnclary — APPROVED** [review]
👍 🙏

**Review by mateoclarke — APPROVED** [review]
🚢

**Comment by johnclary** [comment]
hopefully I didn't create mergenconflicts for you @tillyw when i updated folks pronouns on Monday. i shoulda branched from here.

**Comment by tillyw** [comment]
> hopefully I didn't create merge conflicts for you @tillyw when i updated folks pronouns on Monday. i shoulda branched from here.

I didn't come across any!

**Pull request merged**
