### PR TITLE
Add Strange to team

### PR DESCRIPTION
**Pull request by chiaberry**
also adding headshot for Dipa

closes https://github.com/cityofaustin/atd-data-tech/issues/13148 & https://github.com/cityofaustin/atd-data-tech/issues/13146

https://deploy-preview-72--atd-product.netlify.app/about

### CODE REVIEW

**Review by roseeichelmann — APPROVED** [review]
yay :partying_face:

**Review by dianamartin — APPROVED** [review]

**Comment by amenity** [comment]
@dianamartin - didn't @JBStrange start before Vaishnav and Homer? We've always kept these in chronological order of joining DTS, aside from the DM.

**Comment by chiaberry** [comment]
I believe he did, but I have been adding people in order of the issues
being opened and assigned. I'm happy to move him!

**Review by mddilley — APPROVED** [review]
🎉 🚢

**Pull request merged**
