### PR TITLE
Add Homer and Vaishnav to team

### PR DESCRIPTION
**Pull request by chiaberry**
Closes: https://github.com/cityofaustin/atd-data-tech/issues/12707 and  https://github.com/cityofaustin/atd-data-tech/issues/12977

https://deploy-preview-69--atd-product.netlify.app/about

### CODE REVIEW

**Comment by chiaberry** [comment]
We are still missing Strange on the site and I am not sure who else. I tried looking for an issue to add Strange, but I couldnt find one. His headshot is in the folder though, so I could add him once I get his title and pronouns. @dianamartin & @amenity

**Review by patrickm02L — APPROVED** [review]
Nice! 📸

**Review by mddilley — APPROVED** [review]
🙌 🙏 🚀

**Review by roseeichelmann — APPROVED** [review]
team is lookin sharp ✨🚢

**Pull request merged**
